import { NextResponse } from 'next/server'

export async function POST(request: Request) {
  try {
    const { term } = await request.json()
    
    if (!term) {
      return NextResponse.json({ error: 'Term is required' }, { status: 400 })
    }

    // Mock AI explanations for different terms
    const explanations: Record<string, string> = {
      'impact energy': 'Impact energy is the kinetic energy released when an asteroid strikes Earth, measured in joules or megatons of TNT equivalent.',
      'crater depth': 'Crater depth refers to how deep the impact crater would be, measured from the original surface level.',
      'displacement': 'Displacement measures how much material is ejected upward and outward from the impact site.',
      'seismic magnitude': 'Seismic magnitude indicates the strength of earthquake-like waves generated by the impact, using the moment magnitude scale.'
    }

    const explanation = explanations[term] || `This term "${term}" relates to asteroid impact calculations and measurements.`

    return NextResponse.json({ explanation })
  } catch (error) {
    return NextResponse.json({ error: 'Invalid request' }, { status: 400 })
  }
}
